# Generated by Django 3.1 on 2020-09-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_API', '0004_dataset_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='type_data',
            field=models.JSONField(null=True),
        ),
    ]
